[project]
name = "service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arize-phoenix-otel>=0.17.1",
    "django>=6.1",
    "djangorestframework>=3.18.0",
    "gunicorn>=26.0.0",
    "openinference-semantic-conventions>=0.1.32",
    "opentelemetry-instrumentation-django>=0.65b0",
    "opentelemetry-instrumentation-requests>=0.65b0",
]
