[project]
name = "inference-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "openinference-semantic-conventions>=0.1.32",
    "opentelemetry-exporter-otlp-proto-http>=1.39.0",
    "opentelemetry-instrumentation-fastapi>=0.65b0",
    "opentelemetry-instrumentation-httpx>=0.65b0",
    "opentelemetry-sdk>=1.39.0",
    "transformers>=5.15.0",
    "uvicorn[standard]>=0.52.3",
]
